
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006000
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
ACH
BackOffice
Caleb
Cushing
xenoterracide
lib
Business
PaperlessTrans
RequestPart
Card
Role
State
Client
Identification
CustomFields
Request
Money
AuthorizeCard
Response
IsApproved
TestConnection
EmailAddress
Address
Authorization
NameOnAccount
ProcessACH
Profile
ProcessCard
Check
Phone
